apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-fluentd-config
  namespace: elasticssearch
data:
  fluentd.conf: |
    <source>
      @type tail
      path /usr/share/elasticsearch/logs/*.log
      pos_file /tmp/log.pos
      read_from_head true
      <parse>
        @type regexp
        expression /^(?<msg>.*)$/
      </parse>
      tag graylog2
    </source>

    <filter graylog2.**>
      @type record_transformer
      <record>
        facility "elasticsearch"
        component "elasticsearch"
        facet "elasticsearch"
        tag ${tag}
        namespace "elasticsearch"
      </record>
    </filter>

    <match graylog2.**>
      @type gelf
      host graylog
      port 12201
      protocol udp
    </match>
